// src/components/About/About.jsx
import React from 'react';
import './About.scss';
import { skills } from '../../skills';

const About = () => (
  <div id="about" className='section'>
    <h1 className='section-header'>About Me</h1>
    <div className='about-info'>
      <div>
        <div className='d-flex justify-content-center w-100'>
          <h5 className="introduction">
            I am a Full-Stack Software Developer in the Minneapolis area looking to join your development team.
            I feel passionately about the importance of a clean, responsive, and easy-to-use application.
            I'll help you by bringing that passion to your next big project!
          </h5>
        </div>
      </div>
      <div>
        <div>
          <div className='skills-icons'>
            <div>
              
            </div>
            <div>
              {skills.map(skill => (
                <div className='skill-icon' key={skill.title}>
                  <a href={skill.link}>
                    <img src={skill.logo} className="icon" alt="skill-logo" />
                  </a>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      <div>
        <div xs={10}>
          <button className="resume-btn" href="resume.pdf" download="resume">
            Download Full Resume
          </button>
        </div>
      </div>
      
      
    </div>
  </div>
);

export default About;

// src/app/components/about/about.component.ts
import { Component } from '@angular/core';
import { skills } from '../../data/skills';
import { SectionWrapperComponent } from '../section-wrapper/section-wrapper.component';

@Component({
  selector: 'about',
  imports: [SectionWrapperComponent],
  templateUrl: './about.component.html'
})
export class AboutComponent {
  jobSkills = skills;
}

<section-wrapper id="about" header="About Me">
  <div class="flex justify-between">
    <p class="w-1/3">
      I am a Full-Stack Software Developer in the Minneapolis area looking to join your development team.
      I feel passionately about the importance of a clean, responsive, and easy-to-use application.
      I'll help you by bringing that passion to your next big project!
    </p>
    <div class="flex flex-col items-center gap-8">
      <div class="flex gap-3">
        @for (skill of jobSkills; track skill.title) {
        <a [href]="skill.link">
          <img [src]="skill.logo" alt="skill logo" class="h-16" />
        </a>
        }
      </div>

      <a class="p-button" href="resume.pdf" target="_blank">Download Full Resume</a>
    </div>
  </div>
</section-wrapper>
