// src/components/Home/Home.tsx
import React from 'react';
import './Home.scss';
import { Button, IconButton, Typography } from '@mui/material';
import { Email } from '@mui/icons-material';

const Home = () => (
  <div id='home' className="h-screen flex flex-col justify-center items-center gap-5">
    <img src="img/jakesportrait.jpg" alt="Jake Mitchell Portrait" className="w-96 rounded-full" />
    <Typography fontSize={50}>Jake Mitchell</Typography>
    <div className="flex gap-5">
      <IconButton className="icon" href="mailto:jake@thundercloud.dev">
        <Email className='email-icon' />
        {/* <envelopeicon color="black" size="25" /> */}
      </IconButton>
      <IconButton className="icon" href="https://github.com/jbmitchell7" target="_blank" rel='noreferrer'>
        <img src="img/logos/github.svg" alt="Github Logo" />
      </IconButton>
      <IconButton className="icon" href="https://www.linkedin.com/in/jakebmitchell/" target="_blank" rel='noreferrer'>
        <img src="img/logos/linkedin.svg" alt="LinkedIn Logo" />
      </IconButton>
    </div>
    <Button variant='contained' href="#contact">Hire Me</Button>
    <div className="scroll-prompt flex flex-col items-center">
      <p>Scroll Down</p>
      <svg className="mouse-svg mr-2" width="40" height="45">
        <ellipse cx="25" cy="25" rx="14" ry="18" stroke="black" strokeWidth="2" fill="none" />
        <circle className="mouse-wheel" cx="25" cy="15" r="2" fill="black" />
      </svg>
    </div>
  </div>
);

export default Home;

// src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { ButtonModule } from 'primeng/button';

@Component({
  selector: 'home',
  imports: [ButtonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {}

<div id="home" class="flex flex-col gap-1 justify-center items-center min-h-screen">
  <img src="img/jakesportrait.jpg" alt="Jake Mitchell Portrait" class="w-96 rounded-full" />
  <h1>Jake Mitchell</h1>
  <div class="flex gap-4">
    <a href="mailto:jake@thundercloud.dev" class="p-button">
      <i class="fa-solid fa-envelope"></i>
    </a>
    <a class="p-button" href="https://github.com/jbmitchell7" target="_blank">
      <img src="img/logos/github.svg" alt="Github Logo" />
    </a>
    <a class="p-button" href="https://www.linkedin.com/in/jakebmitchell/" target="_blank">
      <img src="img/logos/linkedin.svg" alt="LinkedIn Logo" />
    </a>
  </div>
  <a class="p-button" href="#contact">Hire Me</a>
  <div class="flex flex-col items-center absolute bottom-[10px]">
    <p>Scroll Down</p>
    <svg class="mouse-svg mr-2" width="40" height="45">
      <ellipse cx="25" cy="25" rx="14" ry="18" stroke="black" strokeWidth="2" fill="none" />
      <circle class="mouse-wheel" cx="25" cy="15" r="2" fill="black" />
    </svg>
  </div>
</div>
