// src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { ButtonModule } from 'primeng/button';

@Component({
  selector: 'home',
  imports: [ButtonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {

}

<div id="home" class="flex flex-col gap-1 h-dvh justify-center items-center">
  <img src="img/jakesportrait.jpg" alt="Jake Mitchell Portrait" class="w-96 rounded-full" />
  <h1 class="text-4xl">Jake Mitchell</h1>
  <div class="flex gap-4">
    <a href="mailto:jake@thundercloud.dev" class="p-button">
      <i class="fa-solid fa-envelope"></i>
    </a>
    <a class="p-button" href="https://github.com/jbmitchell7" target="_blank">
      <img src="img/logos/github.svg" alt="Github Logo" />
    </a>
    <a class="p-button" href="https://www.linkedin.com/in/jakebmitchell/" target="_blank">
      <img src="img/logos/linkedin.svg" alt="LinkedIn Logo" />
    </a>
  </div>
  <a class="p-button" href="#contact">Hire Me</a>
  <div class="flex flex-col items-center absolute bottom-px">
    <p>Scroll Down</p>
    <svg class="mouse-svg mr-2" width="40" height="45">
      <ellipse cx="25" cy="25" rx="14" ry="18" stroke="black" strokeWidth="2" fill="none" />
      <circle class="mouse-wheel" cx="25" cy="15" r="2" fill="black" />
    </svg>
  </div>
</div>

// src/components/Home/Home.jsx
import React from 'react';
import Button from 'react-bootstrap/Button';
import { EnvelopeFill } from 'react-bootstrap-icons';
import './Home.scss';

const Home = () => (
  <div id="home">
    <img src="img/jakesportrait.jpg" alt="Jake Mitchell Portrait" id="portrait" />
    <h1 className='name-header'>Jake Mitchell</h1>
    <div className="social-icons">
      <a className="icon" href="mailto:jbmitchell747@gmail.com">
        <EnvelopeFill color="black" size="25" />
      </a>
      <a className="icon" href="https://github.com/jbmitchell7" target="_blank" rel='noreferrer'>
        <img src="img/logos/github.svg" alt="Github Logo" />
      </a>
      <a className="icon" href="https://www.linkedin.com/in/jakebmitchell/" target="_blank" rel='noreferrer'>
        <img src="img/logos/linkedin.svg" alt="LinkedIn Logo" />
      </a>
    </div>
    <Button className="hire-btn" size="lg" href="#contact">Hire Me</Button>
    <div className="scroll-prompt">
      <p>Scroll Down</p>
      <svg className="mouse-svg" width="40" height="45">
        <ellipse cx="25" cy="25" rx="14" ry="18" stroke="white" strokeWidth="2" fill="none" />
        <circle className="mouse-wheel" cx="25" cy="15" r="2" fill="white" />
      </svg>
    </div>
  </div>
);

export default Home;
